In [ ]:
import pandas as pd
import numpy as np

In [40]:
pd.__version__

'2.3.1'

In [10]:
# Download the dataset
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
 
# Load the dataset using pandas
df = pd.read_csv('car_fuel_efficiency.csv')
df.head()

--2025-10-01 20:44:14--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv’

car_fuel_efficiency 100%[===================>] 853.70K  --.-KB/s    in 0.01s   

2025-10-01 20:44:14 (66.5 MB/s) - ‘car_fuel_efficiency.csv’ saved [874188/874188]

200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv’

car_fuel_efficiency 100%[=======

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [11]:
# Check the number of records in the dataset
df.shape[0]

9704

In [13]:
# Check the number of unique fuel types in the dataset
df['fuel_type'].nunique()

2

In [14]:
# Check how many columns have missing values
df.isnull().any().sum()

np.int64(4)

In [16]:
# Find the maximum fuel efficiency of cars from Asia
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [18]:
# Find the median value of the horsepower column
df['horsepower'].median()

np.float64(149.0)

In [44]:
# Find the most frequent value of the horsepower column
df['horsepower'].mode()[0]

np.float64(152.0)

In [45]:
# Fill missing values in the horsepower column with the most frequent value
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])
df['horsepower'].median()

np.float64(152.0)

In [27]:
# Select all cars from Asia and only columns vehicle_weight and model_year
df_asia = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']]
df_asia.head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [46]:
# NumPy array
X = np.array(df_asia.head(7))
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [34]:
# Compute matrix-matrix multiplication between the transpose of X and X
XTX = X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [35]:
# Invert XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [36]:
# Create array y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# Multiply the inverse of XTX with the transpose of X, then by y
w = XTX_inv.dot(X.T).dot(y)
w

# Sum of all elements of w
w.sum()

np.float64(0.5187709081074016)